[project]
name = "exilepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nextcord>=3.1.1",
    "watchfiles>=1.1.0",
]
